{% set data = load_setup_py_data() %}

package:
  name: lucid
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - lucid = lucid.launcher:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - fuzzywuzzy
    - ophyd
    - pydm
    - pyqt >=5
    - pyqtads
    - pyyaml
    - qtpy
    - typhos
    - happi

test:
  requires:
    - pyqtads
    - pytest
    - pytest-qt
  imports:
    - lucid
  commands:
    - lucid --help

about:
  home: https://github.com/pcdshub/lucid
  dev_url: https://github.com/pcdshub/lucid
  summary: 'SLAC National Accelerator Laboratory: LCLS User Control and Interface Design'
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - klauer
    - hhslepicka
    - zllentz
